### ISSUE TITLE
Direct lifx lan service call from esphome? 

### ISSUE THREAD

**Issue by 10bn** [giantorth/ESPHomeLifx#28]
sry for the question here but I don't know where else to ask this. 

Would it possible (easy) to directly turn on or off LIFX bulbs from esphome without a broker or anything in between?

**Comment by giantorth** [comment]
You can enable the web interface or the API and control the bulbs via the native Esphome interface, it's just right now the lifx side doesn't remain state-aware of changes made externally and will report out it's own last known values.

At some point I had planned on coding a loop to watch for external state changes to update the lifx variables used in the packet responses.

**Comment by 10bn** [comment]
ahh, sry I left to little information about my intentions. 

The Idea was to control (on / off) original LIFX bulbs via the lan api directly from an ESPHome Node like a smart wall switch.
