### ISSUE TITLE
thx for your great esphome code but I have some trouble in compile 

### ISSUE THREAD

**Issue by minsuke** [giantorth/ESPHomeLifx#9]
src/main.cpp: In lambda function:
src/main.cpp:308:33: error: expected type-specifier before 'lifxUdp'
       auto lifxUdpSupport = new lifxUdp();
                                 ^
src/main.cpp:310:29: error: could not convert '{lifxUdpSupport}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::Component*>'
       return {lifxUdpSupport};
                             ^
src/main.cpp:311:3: warning: control reaches end of non-void function [-Wreturn-type]
   });
   ^
*** [/data/h801light/.pioenvs/h801light/src/main.cpp.o] Error 1
========================== [FAILED] Took 2.08 seconds ==========================

What can I correct something ? 

I wish you can help me. 

I am appreciate your awesome code again thank you.

**Comment by giantorth** [comment]
I will need a little more information.  Can you post your YAML file (without passwords) please?

**Comment by minsuke** [comment]
> I will need a little more information. Can you post your YAML file (without passwords) please?

thx I solved it, I have some trouble in libraries thx again : )
